#!/bin/sh
touch tmp/restart.txt
echo "restarting Passenger app"
RAILS_ENV=production rake assets:precompile
kill $(cat tmp/pids/server.pid)
rm tmp/pids/server.pid
bundle exec rails s -e production -p 3000 -d
service apache2 restart